# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            $rootPath: '%kernel.project_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    api_controllers:
        namespace: App\UI\Http\Controller\
        resource: '%kernel.project_dir%/src/UI/Http/Controller/'
        tags: [ 'controller.service_arguments' ]

    _instanceof:
        App\Core\Shared\Application\Messaging\CommandHandlerInterface:
            public: true
            tags:
                - { name: messenger.message_handler }

        App\Core\Shared\Application\Messaging\QueryHandlerInterface:
            public: true
            tags:
                - { name: messenger.message_handler }

        App\Core\Shared\Application\Messaging\EventHandlerInterface:
            public: true
            tags:
                - { name: messenger.message_handler }

        App\Core\Shared\Application\Messaging\KafkaHandlerInterface:
            public: true
            tags:
                - { name: messenger.message_handler }

    App\Core\Shared\Infrastructure\Bus\CommandBus:
        arguments: ['@messenger.bus.command']

    App\Core\Shared\Infrastructure\Bus\EventBus:
        arguments: ['@messenger.bus.event']

    App\Core\Shared\Infrastructure\Bus\QueryBus:
        arguments: ['@messenger.bus.query']

    App\Core\Shared\Infrastructure\Bus\KafkaBus:
        arguments: ['@messenger.bus.kafka']

    Jsor\Doctrine\PostGIS\Event\ORMSchemaEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
