doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            geography:
                class: 'Jsor\Doctrine\PostGIS\Types\GeographyType'
                commented: false
            geometry:
                class: 'Jsor\Doctrine\PostGIS\Types\GeometryType'
                commented: false
        mapping_types:
            _text: string

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Example:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Core/Example/Domain/Entity'
                prefix: 'App\Core\Example\Domain\Entity'
                alias: App
            Auth:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Core/Auth/Domain/Entity'
                prefix: 'App\Core\Auth\Domain\Entity'
                alias: App
